production:
  <<: *default
  # Heroku の DATABASE_URL があればそれを使う
  url: <%= ENV['DATABASE_URL'] %>
  # もしローカルで確認したいときの fallback
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: myapp_production
  username: myapp
  password: password
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
