services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    env_file:
      - .env   # ← ここで指定
    volumes:
      - .:/rails                # ホストのコードをコンテナに反映
      - bundle_data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db          # Rails database.yml で参照
      DATABASE_USER: myapp       # Rails database.yml で参照
      DATABASE_PASSWORD: password
    stdin_open: true
    tty: true
    command: tail -f /dev/null

volumes:
  db_data:
  bundle_data:

