default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: myapp
  password: password
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: myapp_production
